//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTubeTake.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTubeTake.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Button_Dismiss {
            get {
                return ResourceManager.GetString("Button_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick path.
        /// </summary>
        public static string Button_PickPath {
            get {
                return ResourceManager.GetString("Button_PickPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string Button_TryAgain {
            get {
                return ResourceManager.GetString("Button_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you pasted a valid YouTube link..
        /// </summary>
        public static string Error_BadLink_Hint {
            get {
                return ResourceManager.GetString("Error_BadLink_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided URL is not a valid YouTube link..
        /// </summary>
        public static string Error_BadLink_Title {
            get {
                return ResourceManager.GetString("Error_BadLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected.
        /// </summary>
        public static string Error_Detected {
            get {
                return ResourceManager.GetString("Error_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least a video or audio quality before downloading..
        /// </summary>
        public static string Error_DownloadSettings_Hint {
            get {
                return ResourceManager.GetString("Error_DownloadSettings_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video or audio stream was selected for download..
        /// </summary>
        public static string Error_DownloadSettings_Title {
            get {
                return ResourceManager.GetString("Error_DownloadSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place ffmpeg.exe in the application folder and try again..
        /// </summary>
        public static string Error_Ffmpeg_Hint {
            get {
                return ResourceManager.GetString("Error_Ffmpeg_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg.exe was not found in the application directory..
        /// </summary>
        public static string Error_Ffmpeg_Title {
            get {
                return ResourceManager.GetString("Error_Ffmpeg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the file exists..
        /// </summary>
        public static string Error_FileNotFound_Hint {
            get {
                return ResourceManager.GetString("Error_FileNotFound_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string Error_FileNotFound_Title {
            get {
                return ResourceManager.GetString("Error_FileNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO FIX IT.
        /// </summary>
        public static string Error_HowToFix {
            get {
                return ResourceManager.GetString("Error_HowToFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app doesn&apos;t have permission to access the file or folder..
        /// </summary>
        public static string Error_NoAccess_Hint {
            get {
                return ResourceManager.GetString("Error_NoAccess_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Error_NoAccess_Title {
            get {
                return ResourceManager.GetString("Error_NoAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection and try again..
        /// </summary>
        public static string Error_NoConnection_Hint {
            get {
                return ResourceManager.GetString("Error_NoConnection_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        public static string Error_NoConnection_Title {
            get {
                return ResourceManager.GetString("Error_NoConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a link to a specific video, not to a channel or playlist..
        /// </summary>
        public static string Error_NotAVideo_Hint {
            get {
                return ResourceManager.GetString("Error_NotAVideo_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link is not a video.
        /// </summary>
        public static string Error_NotAVideo_Title {
            get {
                return ResourceManager.GetString("Error_NotAVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video requires purchase and cannot be downloaded..
        /// </summary>
        public static string Error_PaidVideo_Hint {
            get {
                return ResourceManager.GetString("Error_PaidVideo_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid video.
        /// </summary>
        public static string Error_PaidVideo_Title {
            get {
                return ResourceManager.GetString("Error_PaidVideo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the app author..
        /// </summary>
        public static string Error_Unknown_Hint {
            get {
                return ResourceManager.GetString("Error_Unknown_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This video is unavailable or has been removed..
        /// </summary>
        public static string Error_VideoUnavailable_Hint {
            get {
                return ResourceManager.GetString("Error_VideoUnavailable_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video unavailable.
        /// </summary>
        public static string Error_VideoUnavailable_Title {
            get {
                return ResourceManager.GetString("Error_VideoUnavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT WENT WRONG.
        /// </summary>
        public static string Error_WhatWentWrong {
            get {
                return ResourceManager.GetString("Error_WhatWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Picker_DefaultLabel {
            get {
                return ResourceManager.GetString("Picker_DefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sound.
        /// </summary>
        public static string Picker_NoSound {
            get {
                return ResourceManager.GetString("Picker_NoSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video.
        /// </summary>
        public static string Picker_NoVideo {
            get {
                return ResourceManager.GetString("Picker_NoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error path.
        /// </summary>
        public static string Setting_PathError {
            get {
                return ResourceManager.GetString("Setting_PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your image path.
        /// </summary>
        public static string Setting_PickImageHint {
            get {
                return ResourceManager.GetString("Setting_PickImageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your video path.
        /// </summary>
        public static string Setting_PickVideoHint {
            get {
                return ResourceManager.GetString("Setting_PickVideoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THUMBNAIL STORAGE.
        /// </summary>
        public static string Setting_ThumbnailStorage {
            get {
                return ResourceManager.GetString("Setting_ThumbnailStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting_Title {
            get {
                return ResourceManager.GetString("Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO STORAGE.
        /// </summary>
        public static string Setting_VideoStorage {
            get {
                return ResourceManager.GetString("Setting_VideoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Status_Downloading {
            get {
                return ResourceManager.GetString("Status_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save thumbnail.
        /// </summary>
        public static string Thumbnail_Save {
            get {
                return ResourceManager.GetString("Thumbnail_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Thumbnail_Saved {
            get {
                return ResourceManager.GetString("Thumbnail_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Thumbnail_Saving {
            get {
                return ResourceManager.GetString("Thumbnail_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Video_AuthorCaption {
            get {
                return ResourceManager.GetString("Video_AuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Video_NameCaption {
            get {
                return ResourceManager.GetString("Video_NameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOUND QUALITY.
        /// </summary>
        public static string Video_SoundQuality {
            get {
                return ResourceManager.GetString("Video_SoundQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO QUALITY.
        /// </summary>
        public static string Video_VideoQuality {
            get {
                return ResourceManager.GetString("Video_VideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a link to get started.
        /// </summary>
        public static string Welcome_Hint {
            get {
                return ResourceManager.GetString("Welcome_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works with YouTube videos and shorts.
        /// </summary>
        public static string Welcome_SubHint {
            get {
                return ResourceManager.GetString("Welcome_SubHint", resourceCulture);
            }
        }
    }
}
