//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTubeTake.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTubeTake.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Welcome_Hint {
            get {
                return ResourceManager.GetString("Welcome_Hint", resourceCulture);
            }
        }

        public static string Welcome_SubHint {
            get {
                return ResourceManager.GetString("Welcome_SubHint", resourceCulture);
            }
        }

        public static string Button_Find {
            get {
                return ResourceManager.GetString("Button_Find", resourceCulture);
            }
        }

        public static string Button_TryAgain {
            get {
                return ResourceManager.GetString("Button_TryAgain", resourceCulture);
            }
        }

        public static string Button_Dismiss {
            get {
                return ResourceManager.GetString("Button_Dismiss", resourceCulture);
            }
        }

        public static string Button_PickPath {
            get {
                return ResourceManager.GetString("Button_PickPath", resourceCulture);
            }
        }

        public static string Error_Detected {
            get {
                return ResourceManager.GetString("Error_Detected", resourceCulture);
            }
        }

        public static string Error_WhatWentWrong {
            get {
                return ResourceManager.GetString("Error_WhatWentWrong", resourceCulture);
            }
        }

        public static string Error_HowToFix {
            get {
                return ResourceManager.GetString("Error_HowToFix", resourceCulture);
            }
        }

        public static string Video_NameCaption {
            get {
                return ResourceManager.GetString("Video_NameCaption", resourceCulture);
            }
        }

        public static string Video_AuthorCaption {
            get {
                return ResourceManager.GetString("Video_AuthorCaption", resourceCulture);
            }
        }

        public static string Video_VideoQuality {
            get {
                return ResourceManager.GetString("Video_VideoQuality", resourceCulture);
            }
        }

        public static string Video_SoundQuality {
            get {
                return ResourceManager.GetString("Video_SoundQuality", resourceCulture);
            }
        }

        public static string Setting_Title {
            get {
                return ResourceManager.GetString("Setting_Title", resourceCulture);
            }
        }

        public static string Setting_VideoStorage {
            get {
                return ResourceManager.GetString("Setting_VideoStorage", resourceCulture);
            }
        }

        public static string Setting_ThumbnailStorage {
            get {
                return ResourceManager.GetString("Setting_ThumbnailStorage", resourceCulture);
            }
        }

        public static string Setting_PickVideoHint {
            get {
                return ResourceManager.GetString("Setting_PickVideoHint", resourceCulture);
            }
        }

        public static string Setting_PickImageHint {
            get {
                return ResourceManager.GetString("Setting_PickImageHint", resourceCulture);
            }
        }

        public static string Setting_PathError {
            get {
                return ResourceManager.GetString("Setting_PathError", resourceCulture);
            }
        }

        public static string Status_Downloading {
            get {
                return ResourceManager.GetString("Status_Downloading", resourceCulture);
            }
        }

        public static string Status_Done {
            get {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }

        public static string Picker_DefaultLabel {
            get {
                return ResourceManager.GetString("Picker_DefaultLabel", resourceCulture);
            }
        }

        public static string Picker_NoVideo {
            get {
                return ResourceManager.GetString("Picker_NoVideo", resourceCulture);
            }
        }

        public static string Picker_NoSound {
            get {
                return ResourceManager.GetString("Picker_NoSound", resourceCulture);
            }
        }

        public static string Thumbnail_Save {
            get {
                return ResourceManager.GetString("Thumbnail_Save", resourceCulture);
            }
        }

        public static string Thumbnail_Saving {
            get {
                return ResourceManager.GetString("Thumbnail_Saving", resourceCulture);
            }
        }

        public static string Thumbnail_Saved {
            get {
                return ResourceManager.GetString("Thumbnail_Saved", resourceCulture);
            }
        }

        public static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }

        public static string Error_NoConnection_Title {
            get {
                return ResourceManager.GetString("Error_NoConnection_Title", resourceCulture);
            }
        }

        public static string Error_NoConnection_Hint {
            get {
                return ResourceManager.GetString("Error_NoConnection_Hint", resourceCulture);
            }
        }

        public static string Error_FileNotFound_Title {
            get {
                return ResourceManager.GetString("Error_FileNotFound_Title", resourceCulture);
            }
        }

        public static string Error_FileNotFound_Hint {
            get {
                return ResourceManager.GetString("Error_FileNotFound_Hint", resourceCulture);
            }
        }

        public static string Error_NoAccess_Title {
            get {
                return ResourceManager.GetString("Error_NoAccess_Title", resourceCulture);
            }
        }

        public static string Error_NoAccess_Hint {
            get {
                return ResourceManager.GetString("Error_NoAccess_Hint", resourceCulture);
            }
        }

        public static string Error_VideoUnavailable_Title {
            get {
                return ResourceManager.GetString("Error_VideoUnavailable_Title", resourceCulture);
            }
        }

        public static string Error_VideoUnavailable_Hint {
            get {
                return ResourceManager.GetString("Error_VideoUnavailable_Hint", resourceCulture);
            }
        }

        public static string Error_PaidVideo_Title {
            get {
                return ResourceManager.GetString("Error_PaidVideo_Title", resourceCulture);
            }
        }

        public static string Error_PaidVideo_Hint {
            get {
                return ResourceManager.GetString("Error_PaidVideo_Hint", resourceCulture);
            }
        }

        public static string Error_BadLink_Title {
            get {
                return ResourceManager.GetString("Error_BadLink_Title", resourceCulture);
            }
        }

        public static string Error_BadLink_Hint {
            get {
                return ResourceManager.GetString("Error_BadLink_Hint", resourceCulture);
            }
        }

        public static string Error_DownloadSettings_Title {
            get {
                return ResourceManager.GetString("Error_DownloadSettings_Title", resourceCulture);
            }
        }

        public static string Error_DownloadSettings_Hint {
            get {
                return ResourceManager.GetString("Error_DownloadSettings_Hint", resourceCulture);
            }
        }

        public static string Error_Ffmpeg_Title {
            get {
                return ResourceManager.GetString("Error_Ffmpeg_Title", resourceCulture);
            }
        }

        public static string Error_Ffmpeg_Hint {
            get {
                return ResourceManager.GetString("Error_Ffmpeg_Hint", resourceCulture);
            }
        }

        public static string Error_Unknown_Hint {
            get {
                return ResourceManager.GetString("Error_Unknown_Hint", resourceCulture);
            }
        }
    }
}
